package com.newtrendz.pass.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@Data
@Document(collection = "memberships")
public class Membership {

    @Id
    private String id; // This field will automatically be generated by MongoDB
    private String name;
    private String description;
    private List<Offer> offers;
    private String qrCode; // You may want to keep this if you're still generating QR codes

    public Membership() {}

    public Membership(String name, String description, List<Offer> offers, String qrCode) {
        this.name = name;
        this.description = description;
        this.offers = offers;
        this.qrCode = qrCode;
    }

    @Data
    public static class Offer {
        private String name;
        private double price;
        private String details;
        private String description;

        public Offer() {}

        public Offer(String name, double price, String details, String description) {
            this.name = name;
            this.price = price;
            this.details = details;
            this.description = description;
        }
    }
}
